name: myCI

on:
  workflow_dispatch:
  #push:
    #branches: master
  #pull_request:
    #branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angular 

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #- name: Install dependencies
        #run: npm install
      - run: npm ci  
      - run: npm run build
      - run: npm run test -- --watch=false --browsers=ChromeHeadless
      #- run: npm run test -- --configuration=ci
      #- run: npm run e2e -- --configuration=ci
      - run: npm run e2e
      - run: npm run lint
